// Generated by scripts/build-maps.rb — do not edit.
import m0 from "./acadsin-zho-Hani-Latn-2002.json" with { type: "json" }
import m1 from "./alalc-amh-Ethi-Latn-1997.json" with { type: "json" }
import m2 from "./alalc-amh-Ethi-Latn-2011.json" with { type: "json" }
import m3 from "./alalc-ara-Arab-Latn-1997.json" with { type: "json" }
import m4 from "./alalc-asm-Deva-Latn-1997.json" with { type: "json" }
import m5 from "./alalc-asm-Deva-Latn-2012.json" with { type: "json" }
import m6 from "./alalc-aze-Arab-Latn-1997.json" with { type: "json" }
import m7 from "./alalc-aze-Cyrl-Latn-1997.json" with { type: "json" }
import m8 from "./alalc-bel-Cyrl-Latn-1997.json" with { type: "json" }
import m9 from "./alalc-ben-Beng-Latn-1997.json" with { type: "json" }
import m10 from "./alalc-ben-Beng-Latn-2017.json" with { type: "json" }
import m11 from "./alalc-bul-Cyrl-Latn-1997.json" with { type: "json" }
import m12 from "./alalc-div-Thaa-Latn-1997.json" with { type: "json" }
import m13 from "./alalc-div-Thaa-Latn-2012.json" with { type: "json" }
import m14 from "./alalc-ell-Grek-Latn-1997.json" with { type: "json" }
import m15 from "./alalc-ell-Grek-Latn-2010.json" with { type: "json" }
import m16 from "./alalc-fas-Arab-Latn-1997.json" with { type: "json" }
import m17 from "./alalc-guj-Gujr-Latn-1997.json" with { type: "json" }
import m18 from "./alalc-guj-Gujr-Latn-2011.json" with { type: "json" }
import m19 from "./alalc-hin-Deva-Latn-1997.json" with { type: "json" }
import m20 from "./alalc-hin-Deva-Latn-2011.json" with { type: "json" }
import m21 from "./alalc-kan-Kana-Latn-1997.json" with { type: "json" }
import m22 from "./alalc-kan-Kana-Latn-2011.json" with { type: "json" }
import m23 from "./alalc-kat-Geok-Latn-1997.json" with { type: "json" }
import m24 from "./alalc-kat-Geok-Latn-2011.json" with { type: "json" }
import m25 from "./alalc-kat-Geor-Latn-1997.json" with { type: "json" }
import m26 from "./alalc-kat-Geor-Latn-2011.json" with { type: "json" }
import m27 from "./alalc-kor-Hang-Latn-1997.json" with { type: "json" }
import m28 from "./alalc-mal-Mlym-Latn-1997.json" with { type: "json" }
import m29 from "./alalc-mal-Mlym-Latn-2012.json" with { type: "json" }
import m30 from "./alalc-mar-Deva-Latn-1997.json" with { type: "json" }
import m31 from "./alalc-mar-Deva-Latn-2011.json" with { type: "json" }
import m32 from "./alalc-mkd-Cyrl-Latn-1997.json" with { type: "json" }
import m33 from "./alalc-mkd-Cyrl-Latn-2013.json" with { type: "json" }
import m34 from "./alalc-mon-Cyrl-Latn-1997.json" with { type: "json" }
import m35 from "./alalc-ori-Orya-Latn-1997.json" with { type: "json" }
import m36 from "./alalc-ori-Orya-Latn-2011.json" with { type: "json" }
import m37 from "./alalc-pan-Guru-Latn-1997.json" with { type: "json" }
import m38 from "./alalc-pan-Guru-Latn-2011.json" with { type: "json" }
import m39 from "./alalc-pli-Deva-Latn-2012.json" with { type: "json" }
import m40 from "./alalc-pra-Deva-Latn-2012.json" with { type: "json" }
import m41 from "./alalc-rus-Cyrl-Latn-1997.json" with { type: "json" }
import m42 from "./alalc-rus-Cyrl-Latn-2012.json" with { type: "json" }
import m43 from "./alalc-san-Deva-Latn-2012.json" with { type: "json" }
import m44 from "./alalc-sin-Sinh-Latn-1997.json" with { type: "json" }
import m45 from "./alalc-sin-Sinh-Latn-2011.json" with { type: "json" }
import m46 from "./alalc-srp-Cyrl-Latn-1997.json" with { type: "json" }
import m47 from "./alalc-srp-Cyrl-Latn-2013.json" with { type: "json" }
import m48 from "./alalc-tam-Taml-Latn-1997.json" with { type: "json" }
import m49 from "./alalc-tam-Taml-Latn-2011.json" with { type: "json" }
import m50 from "./alalc-tel-Telu-Latn-1997.json" with { type: "json" }
import m51 from "./alalc-tel-Telu-Latn-2011.json" with { type: "json" }
import m52 from "./alalc-tir-Ethi-Latn-1997.json" with { type: "json" }
import m53 from "./alalc-tir-Ethi-Latn-2011.json" with { type: "json" }
import m54 from "./alalc-ukr-Cyrl-Latn-1997.json" with { type: "json" }
import m55 from "./alalc-ukr-Cyrl-Latn-2011.json" with { type: "json" }
import m56 from "./apcbg-bul-Cyrl-Latn-1995.json" with { type: "json" }
import m57 from "./az-aze-Cyrl-Latn-1939.json" with { type: "json" }
import m58 from "./az-aze-Cyrl-Latn-1958.json" with { type: "json" }
import m59 from "./bas-rus-Cyrl-Latn-2017-bss.json" with { type: "json" }
import m60 from "./bas-rus-Cyrl-Latn-2017-oss.json" with { type: "json" }
import m61 from "./bgn-jpn-Hrkt-Latn-1962.json" with { type: "json" }
import m62 from "./bgn-kor-Hang-Latn-1943.json" with { type: "json" }
import m63 from "./bgn-kor-Kore-Latn-1943.json" with { type: "json" }
import m64 from "./bgna-bul-Cyrl-Latn-2006.json" with { type: "json" }
import m65 from "./bgna-bul-Cyrl-Latn-2009.json" with { type: "json" }
import m66 from "./bgnpcgn-amh-Ethi-Latn-1967.json" with { type: "json" }
import m67 from "./bgnpcgn-ara-Arab-Latn-1956.json" with { type: "json" }
import m68 from "./bgnpcgn-arm-Armn-Latn-1981.json" with { type: "json" }
import m69 from "./bgnpcgn-aze-Cyrl-Latn-1993.json" with { type: "json" }
import m70 from "./bgnpcgn-bak-Cyrl-Latn-2007.json" with { type: "json" }
import m71 from "./bgnpcgn-bal-Arab-Latn-2008.json" with { type: "json" }
import m72 from "./bgnpcgn-bel-Cyrl-Latn-1979.json" with { type: "json" }
import m73 from "./bgnpcgn-bul-Cyrl-Latn-1952.json" with { type: "json" }
import m74 from "./bgnpcgn-bul-Cyrl-Latn-2013.json" with { type: "json" }
import m75 from "./bgnpcgn-che-Cyrl-Latn-2008.json" with { type: "json" }
import m76 from "./bgnpcgn-deu-Latn-Latn-2000.json" with { type: "json" }
import m77 from "./bgnpcgn-div-Thaa-Latn-1972.json" with { type: "json" }
import m78 from "./bgnpcgn-div-Thaa-Latn-1988.json" with { type: "json" }
import m79 from "./bgnpcgn-ell-Grek-Latn-1962.json" with { type: "json" }
import m80 from "./bgnpcgn-ell-Grek-Latn-1996.json" with { type: "json" }
import m81 from "./bgnpcgn-fao-Latn-Latn-1964.json" with { type: "json" }
import m82 from "./bgnpcgn-fao-Latn-Latn-1968.json" with { type: "json" }
import m83 from "./bgnpcgn-fas-Arab-Latn-1956.json" with { type: "json" }
import m84 from "./bgnpcgn-isl-Latn-Latn-1964.json" with { type: "json" }
import m85 from "./bgnpcgn-isl-Latn-Latn-1968.json" with { type: "json" }
import m86 from "./bgnpcgn-jpn-Hrkt-Latn-1976.json" with { type: "json" }
import m87 from "./bgnpcgn-kat-Geor-Latn-1981.json" with { type: "json" }
import m88 from "./bgnpcgn-kat-Geor-Latn-2009.json" with { type: "json" }
import m89 from "./bgnpcgn-kaz-Cyrl-Latn-1979.json" with { type: "json" }
import m90 from "./bgnpcgn-kir-Cyrl-Latn-1979.json" with { type: "json" }
import m91 from "./bgnpcgn-kor-Hang-Latn-kn-1945.json" with { type: "json" }
import m92 from "./bgnpcgn-kor-Hang-Latn-rok-2011.json" with { type: "json" }
import m93 from "./bgnpcgn-kor-Kore-Latn-rok-2011.json" with { type: "json" }
import m94 from "./bgnpcgn-kur-Arab-Latn-2007.json" with { type: "json" }
import m95 from "./bgnpcgn-mkd-Cyrl-Latn-1981.json" with { type: "json" }
import m96 from "./bgnpcgn-mkd-Cyrl-Latn-2013.json" with { type: "json" }
import m97 from "./bgnpcgn-mon-Cyrl-Latn-1964.json" with { type: "json" }
import m98 from "./bgnpcgn-nep-Deva-Latn-2011.json" with { type: "json" }
import m99 from "./bgnpcgn-per-Arab-Latn-1958.json" with { type: "json" }
import m100 from "./bgnpcgn-prs-Arab-Latn-2007.json" with { type: "json" }
import m101 from "./bgnpcgn-prs-Arab-Latn-yaghoubi.json" with { type: "json" }
import m102 from "./bgnpcgn-pus-Arab-Latn-1968.json" with { type: "json" }
import m103 from "./bgnpcgn-ron-Cyrl-Latn-2002.json" with { type: "json" }
import m104 from "./bgnpcgn-rue-Cyrl-Latn-2016.json" with { type: "json" }
import m105 from "./bgnpcgn-rus-Cyrl-Latn-1947.json" with { type: "json" }
import m106 from "./bgnpcgn-sme-Latn-Latn-1984.json" with { type: "json" }
import m107 from "./bgnpcgn-srp-Cyrl-Latn-1962.json" with { type: "json" }
import m108 from "./bgnpcgn-srp-Cyrl-Latn-2005.json" with { type: "json" }
import m109 from "./bgnpcgn-tat-Cyrl-Latn-2007.json" with { type: "json" }
import m110 from "./bgnpcgn-tgk-Cyrl-Latn-1994.json" with { type: "json" }
import m111 from "./bgnpcgn-tir-Ethi-Latn-2007.json" with { type: "json" }
import m112 from "./bgnpcgn-tuk-Cyrl-Latn-1979.json" with { type: "json" }
import m113 from "./bgnpcgn-tuk-Cyrl-Latn-1993.json" with { type: "json" }
import m114 from "./bgnpcgn-ukr-Cyrl-Latn-1965.json" with { type: "json" }
import m115 from "./bgnpcgn-ukr-Cyrl-Latn-2019.json" with { type: "json" }
import m116 from "./bgnpcgn-urd-Arab-Latn-2007.json" with { type: "json" }
import m117 from "./bgnpcgn-uzb-Cyrl-Latn-1979.json" with { type: "json" }
import m118 from "./bgnpcgn-uzb-Cyrl-Latn-2000.json" with { type: "json" }
import m119 from "./bgnpcgn-zho-Hans-Latn-1979.json" with { type: "json" }
import m120 from "./bis-asm-Beng-Latn-13194-1991.json" with { type: "json" }
import m121 from "./bis-ben-Beng-Latn-13194-1991.json" with { type: "json" }
import m122 from "./bis-dev-Deva-Latn-13194-1991.json" with { type: "json" }
import m123 from "./bis-guj-Gujr-Latn-13194-1991.json" with { type: "json" }
import m124 from "./bis-kan-Kana-Latn-13194-1991.json" with { type: "json" }
import m125 from "./bis-mlm-Mlym-Latn-13194-1991.json" with { type: "json" }
import m126 from "./bis-ori-Orya-Latn-13194-1991.json" with { type: "json" }
import m127 from "./bis-pnj-Guru-Latn-13194-1991.json" with { type: "json" }
import m128 from "./bis-tel-Telu-Latn-13194-1991.json" with { type: "json" }
import m129 from "./bis-tml-Taml-Latn-13194-1991.json" with { type: "json" }
import m130 from "./by-bel-Cyrl-Latn-1998.json" with { type: "json" }
import m131 from "./by-bel-Cyrl-Latn-2007.json" with { type: "json" }
import m132 from "./din-grc-Grek-Latn-31634-2011-t1.json" with { type: "json" }
import m133 from "./din-hin-Deva-Latn-33904-2018.json" with { type: "json" }
import m134 from "./din-kat-Geor-Latn-32707-2010.json" with { type: "json" }
import m135 from "./din-mar-Deva-Latn-33904-2018.json" with { type: "json" }
import m136 from "./din-nep-Deva-Latn-33904-2018.json" with { type: "json" }
import m137 from "./din-pli-Deva-Latn-33904-2018.json" with { type: "json" }
import m138 from "./din-pra-Deva-Latn-33904-2018.json" with { type: "json" }
import m139 from "./din-san-Deva-Latn-33904-2018.json" with { type: "json" }
import m140 from "./din-tam-Taml-Latn-33903-2016.json" with { type: "json" }
import m141 from "./dos-nep-Deva-Latn-1997.json" with { type: "json" }
import m142 from "./elot-ell-Grek-Latn-743-1982-tl.json" with { type: "json" }
import m143 from "./elot-ell-Grek-Latn-743-1982-ts.json" with { type: "json" }
import m144 from "./elot-ell-Grek-Latn-743-2001-tl.json" with { type: "json" }
import m145 from "./elot-ell-Grek-Latn-743-2001-ts.json" with { type: "json" }
import m146 from "./ggg-kat-Geor-Latn-2002.json" with { type: "json" }
import m147 from "./gki-bel-Cyrl-Latn-1992.json" with { type: "json" }
import m148 from "./gki-bel-Cyrl-Latn-2000.json" with { type: "json" }
import m149 from "./gost-rus-Cyrl-Latn-16876-71-1983.json" with { type: "json" }
import m150 from "./gost-rus-Cyrl-Latn-7.79-2000-2002.json" with { type: "json" }
import m151 from "./hk-yue-Hani-Latn-1888.json" with { type: "json" }
import m152 from "./icao-bel-Cyrl-Latn-9303.json" with { type: "json" }
import m153 from "./icao-bul-Cyrl-Latn-9303.json" with { type: "json" }
import m154 from "./icao-fas-Arab-Latn-9303.json" with { type: "json" }
import m155 from "./icao-heb-Hebr-Latn-9303.json" with { type: "json" }
import m156 from "./icao-mkd-Cyrl-Latn-9303.json" with { type: "json" }
import m157 from "./icao-rus-Cyrl-Latn-9303.json" with { type: "json" }
import m158 from "./icao-srp-Cyrl-Latn-9303.json" with { type: "json" }
import m159 from "./icao-ukr-Cyrl-Latn-9303.json" with { type: "json" }
import m160 from "./iso-ara-Arab-Latn-233-1984.json" with { type: "json" }
import m161 from "./iso-ara-Arab-Latn-233-2-1993.json" with { type: "json" }
import m162 from "./iso-asm-Beng-Latn-15919-2001.json" with { type: "json" }
import m163 from "./iso-ben-Beng-Latn-15919-2001.json" with { type: "json" }
import m164 from "./iso-ell-Grek-Latn-843-1997-t1.json" with { type: "json" }
import m165 from "./iso-ell-Grek-Latn-843-1997-t2.json" with { type: "json" }
import m166 from "./iso-guj-Gujr-Latn-15919-2001.json" with { type: "json" }
import m167 from "./iso-hin-Deva-Latn-15919-2001.json" with { type: "json" }
import m168 from "./iso-inc-Deva-Latn-15919-2001.json" with { type: "json" }
import m169 from "./iso-jpn-Hrkt-Latn-3602-1989.json" with { type: "json" }
import m170 from "./iso-kan-Kana-Latn-15919-2001.json" with { type: "json" }
import m171 from "./iso-kat-Geor-Latn-9984-1996.json" with { type: "json" }
import m172 from "./iso-kor-Hang-Latn-1996-method1.json" with { type: "json" }
import m173 from "./iso-kor-Hang-Latn-1996-method2.json" with { type: "json" }
import m174 from "./iso-mal-Mlym-Latn-15919-2001.json" with { type: "json" }
import m175 from "./iso-mar-Deva-Latn-15919-2001.json" with { type: "json" }
import m176 from "./iso-nep-Deva-Latn-15919-2001.json" with { type: "json" }
import m177 from "./iso-ori-Orya-Latn-15919-2001.json" with { type: "json" }
import m178 from "./iso-pan-Guru-Latn-15919-2001.json" with { type: "json" }
import m179 from "./iso-pli-Beng-Latn-15919-2001.json" with { type: "json" }
import m180 from "./iso-pli-Deva-Latn-15919-2001.json" with { type: "json" }
import m181 from "./iso-pli-Sinh-Latn-15919-2001.json" with { type: "json" }
import m182 from "./iso-pli-Thai-Latn-15919-2001.json" with { type: "json" }
import m183 from "./iso-pra-Deva-Latn-15919-2001.json" with { type: "json" }
import m184 from "./iso-prs-Arab-Latn-233-3-1999.json" with { type: "json" }
import m185 from "./iso-rus-Cyrl-Latn-9-1995.json" with { type: "json" }
import m186 from "./iso-san-Deva-Latn-15919-2001.json" with { type: "json" }
import m187 from "./iso-tam-Taml-Latn-15919-2001.json" with { type: "json" }
import m188 from "./iso-tel-Telu-Latn-15919-2001.json" with { type: "json" }
import m189 from "./iso-tha-Thai-Latn-11940-1998.json" with { type: "json" }
import m190 from "./kp-kor-Hang-Latn-2002.json" with { type: "json" }
import m191 from "./lshk-yue-Hani-Latn-jyutping-1993.json" with { type: "json" }
import m192 from "./masm-mon-Cyrl-Latn-5217-2012.json" with { type: "json" }
import m193 from "./masm-mon-Latn-Cyrl-5217-2012.json" with { type: "json" }
import m194 from "./mext-jpn-Hrkt-Latn-1954.json" with { type: "json" }
import m195 from "./moct-kor-Hang-Latn-2000.json" with { type: "json" }
import m196 from "./mofa-jpn-Hrkt-Latn-1989.json" with { type: "json" }
import m197 from "./mv-div-Thaa-Latn-1987.json" with { type: "json" }
import m198 from "./mvd-bel-Cyrl-Latn-2008.json" with { type: "json" }
import m199 from "./mvd-bel-Cyrl-Latn-2010.json" with { type: "json" }
import m200 from "./mvd-rus-Cyrl-Latn-2008.json" with { type: "json" }
import m201 from "./mvd-rus-Cyrl-Latn-2010.json" with { type: "json" }
import m202 from "./odni-ara-Arab-Latn-2004.json" with { type: "json" }
import m203 from "./odni-ara-Arab-Latn-2015.json" with { type: "json" }
import m204 from "./odni-aze-Cyrl-Latn-2015.json" with { type: "json" }
import m205 from "./odni-bel-Cyrl-Latn-2015.json" with { type: "json" }
import m206 from "./odni-bul-Cyrl-Latn-2005.json" with { type: "json" }
import m207 from "./odni-bul-Cyrl-Latn-2015.json" with { type: "json" }
import m208 from "./odni-che-Cyrl-Latn-2015.json" with { type: "json" }
import m209 from "./odni-fas-Arab-Latn-2004.json" with { type: "json" }
import m210 from "./odni-fas-Arab-Latn-2015.json" with { type: "json" }
import m211 from "./odni-hin-Deva-Latn-2004.json" with { type: "json" }
import m212 from "./odni-hin-Deva-Latn-2015.json" with { type: "json" }
import m213 from "./odni-kat-Geor-Latn-2015.json" with { type: "json" }
import m214 from "./odni-kaz-Cyrl-Latn-2015.json" with { type: "json" }
import m215 from "./odni-kir-Cyrl-Latn-2015.json" with { type: "json" }
import m216 from "./odni-kor-Hang-Latn-2015.json" with { type: "json" }
import m217 from "./odni-mkd-Cyrl-Latn-2005.json" with { type: "json" }
import m218 from "./odni-mkd-Cyrl-Latn-2015.json" with { type: "json" }
import m219 from "./odni-prs-Arab-Latn-2004.json" with { type: "json" }
import m220 from "./odni-prs-Arab-Latn-2015.json" with { type: "json" }
import m221 from "./odni-pus-Arab-Latn-2011.json" with { type: "json" }
import m222 from "./odni-rus-Cyrl-Latn-2015.json" with { type: "json" }
import m223 from "./odni-srp-Cyrl-Latn-2005.json" with { type: "json" }
import m224 from "./odni-srp-Cyrl-Latn-2015.json" with { type: "json" }
import m225 from "./odni-tat-Cyrl-Latn-2015.json" with { type: "json" }
import m226 from "./odni-tgk-Cyrl-Latn-2015.json" with { type: "json" }
import m227 from "./odni-tuk-Cyrl-Latn-2015.json" with { type: "json" }
import m228 from "./odni-uig-Cyrl-Latn-2015.json" with { type: "json" }
import m229 from "./odni-ukr-Cyrl-Latn-2015.json" with { type: "json" }
import m230 from "./odni-urd-Arab-Latn-2015.json" with { type: "json" }
import m231 from "./odni-uzb-Cyrl-Latn-2015.json" with { type: "json" }
import m232 from "./sac-zho-Hans-Latn-1979.json" with { type: "json" }
import m233 from "./sasm-mon-Mong-Latn-general-1978.json" with { type: "json" }
import m234 from "./sasm-mon-Mong-Latn-phonetic-1978.json" with { type: "json" }
import m235 from "./ses-ara-Arab-Latn-1930.json" with { type: "json" }
import m236 from "./stategeocadastre-ukr-Cyrl-Latn-1993.json" with { type: "json" }
import m237 from "./ua-ukr-Cyrl-Latn-1996.json" with { type: "json" }
import m238 from "./ua-ukr-Cyrl-Latn-2007.json" with { type: "json" }
import m239 from "./ua-ukr-Cyrl-Latn-2010.json" with { type: "json" }
import m240 from "./un-amh-Ethi-Latn-2016.json" with { type: "json" }
import m241 from "./un-ara-Arab-Latn-1971.json" with { type: "json" }
import m242 from "./un-ara-Arab-Latn-1972.json" with { type: "json" }
import m243 from "./un-ara-Arab-Latn-2017.json" with { type: "json" }
import m244 from "./un-asm-Beng-Latn-1972.json" with { type: "json" }
import m245 from "./un-bel-Cyrl-Latn-2007.json" with { type: "json" }
import m246 from "./un-ben-Beng-Latn-2016.json" with { type: "json" }
import m247 from "./un-bul-Cyrl-Latn-1977.json" with { type: "json" }
import m248 from "./un-ell-Grek-Latn-1987-phonetic.json" with { type: "json" }
import m249 from "./un-ell-Grek-Latn-1987-tl.json" with { type: "json" }
import m250 from "./un-ell-Grek-Latn-1987-ts.json" with { type: "json" }
import m251 from "./un-guj-Gujr-Latn-1972.json" with { type: "json" }
import m252 from "./un-hin-Deva-Latn-2016.json" with { type: "json" }
import m253 from "./un-kan-Kana-Latn-2016.json" with { type: "json" }
import m254 from "./un-mal-Mlym-Latn-1972.json" with { type: "json" }
import m255 from "./un-mar-Deva-Latn-2016.json" with { type: "json" }
import m256 from "./un-mkd-Cyrl-Latn-1977.json" with { type: "json" }
import m257 from "./un-mon-Mong-Latn-general-2013.json" with { type: "json" }
import m258 from "./un-mon-Mong-Latn-phonetic-2013.json" with { type: "json" }
import m259 from "./un-nep-Deva-Latn-1972.json" with { type: "json" }
import m260 from "./un-nep-Deva-Latn-2013.json" with { type: "json" }
import m261 from "./un-ori-Orya-Latn-1972.json" with { type: "json" }
import m262 from "./un-pan-Guru-Latn-1972.json" with { type: "json" }
import m263 from "./un-prs-Arab-Latn-1967.json" with { type: "json" }
import m264 from "./un-rus-Cyrl-Latn-1987.json" with { type: "json" }
import m265 from "./un-sin-Sinh-Latn-1972.json" with { type: "json" }
import m266 from "./un-srp-Cyrl-Latn-1997.json" with { type: "json" }
import m267 from "./un-tam-Taml-Latn-1972.json" with { type: "json" }
import m268 from "./un-tel-Telu-Latn-1972.json" with { type: "json" }
import m269 from "./un-ukr-Cyrl-Latn-1998.json" with { type: "json" }
import m270 from "./un-ukr-Cyrl-Latn-2012.json" with { type: "json" }
import m271 from "./un-urd-Arab-Latn-1972.json" with { type: "json" }
import m272 from "./var-amh-Ethi-Latn-eae-2003.json" with { type: "json" }
import m273 from "./var-ara-Arab-Arab-rababa.json" with { type: "json" }
import m274 from "./var-gez-Ethi-Latn-eae-2003.json" with { type: "json" }
import m275 from "./var-hin-Deva-Latn-hunterian-1872.json" with { type: "json" }
import m276 from "./var-jpn-Hrkt-Latn-hepburn-1886.json" with { type: "json" }
import m277 from "./var-jpn-Hrkt-Latn-hepburn-1954.json" with { type: "json" }
import m278 from "./var-kor-Hang-Hang-jamo.json" with { type: "json" }
import m279 from "./var-kor-Hang-Latn-mr-1939.json" with { type: "json" }
import m280 from "./var-kor-Kore-Hang-2013.json" with { type: "json" }
import m281 from "./var-kor-Kore-Latn-mr-1939.json" with { type: "json" }
import m282 from "./var-mar-Deva-Latn-hunterian-1872.json" with { type: "json" }
import m283 from "./var-mon-Mong-Latn-1930.json" with { type: "json" }
import m284 from "./var-mon-Mong-Latn-lessing.json" with { type: "json" }
import m285 from "./var-mon-Mong-Latn-vpmc.json" with { type: "json" }
import m286 from "./var-pra-Deva-Latn-iast-1912.json" with { type: "json" }
import m287 from "./var-san-Deva-Latn-iast-1912.json" with { type: "json" }
import m288 from "./var-zho-Hani-Latn-wd-1979.json" with { type: "json" }

export const systemCodes = [
  "acadsin-zho-Hani-Latn-2002",
  "alalc-amh-Ethi-Latn-1997",
  "alalc-amh-Ethi-Latn-2011",
  "alalc-ara-Arab-Latn-1997",
  "alalc-asm-Deva-Latn-1997",
  "alalc-asm-Deva-Latn-2012",
  "alalc-aze-Arab-Latn-1997",
  "alalc-aze-Cyrl-Latn-1997",
  "alalc-bel-Cyrl-Latn-1997",
  "alalc-ben-Beng-Latn-1997",
  "alalc-ben-Beng-Latn-2017",
  "alalc-bul-Cyrl-Latn-1997",
  "alalc-div-Thaa-Latn-1997",
  "alalc-div-Thaa-Latn-2012",
  "alalc-ell-Grek-Latn-1997",
  "alalc-ell-Grek-Latn-2010",
  "alalc-fas-Arab-Latn-1997",
  "alalc-guj-Gujr-Latn-1997",
  "alalc-guj-Gujr-Latn-2011",
  "alalc-hin-Deva-Latn-1997",
  "alalc-hin-Deva-Latn-2011",
  "alalc-kan-Kana-Latn-1997",
  "alalc-kan-Kana-Latn-2011",
  "alalc-kat-Geok-Latn-1997",
  "alalc-kat-Geok-Latn-2011",
  "alalc-kat-Geor-Latn-1997",
  "alalc-kat-Geor-Latn-2011",
  "alalc-kor-Hang-Latn-1997",
  "alalc-mal-Mlym-Latn-1997",
  "alalc-mal-Mlym-Latn-2012",
  "alalc-mar-Deva-Latn-1997",
  "alalc-mar-Deva-Latn-2011",
  "alalc-mkd-Cyrl-Latn-1997",
  "alalc-mkd-Cyrl-Latn-2013",
  "alalc-mon-Cyrl-Latn-1997",
  "alalc-ori-Orya-Latn-1997",
  "alalc-ori-Orya-Latn-2011",
  "alalc-pan-Guru-Latn-1997",
  "alalc-pan-Guru-Latn-2011",
  "alalc-pli-Deva-Latn-2012",
  "alalc-pra-Deva-Latn-2012",
  "alalc-rus-Cyrl-Latn-1997",
  "alalc-rus-Cyrl-Latn-2012",
  "alalc-san-Deva-Latn-2012",
  "alalc-sin-Sinh-Latn-1997",
  "alalc-sin-Sinh-Latn-2011",
  "alalc-srp-Cyrl-Latn-1997",
  "alalc-srp-Cyrl-Latn-2013",
  "alalc-tam-Taml-Latn-1997",
  "alalc-tam-Taml-Latn-2011",
  "alalc-tel-Telu-Latn-1997",
  "alalc-tel-Telu-Latn-2011",
  "alalc-tir-Ethi-Latn-1997",
  "alalc-tir-Ethi-Latn-2011",
  "alalc-ukr-Cyrl-Latn-1997",
  "alalc-ukr-Cyrl-Latn-2011",
  "apcbg-bul-Cyrl-Latn-1995",
  "az-aze-Cyrl-Latn-1939",
  "az-aze-Cyrl-Latn-1958",
  "bas-rus-Cyrl-Latn-2017-bss",
  "bas-rus-Cyrl-Latn-2017-oss",
  "bgn-jpn-Hrkt-Latn-1962",
  "bgn-kor-Hang-Latn-1943",
  "bgn-kor-Kore-Latn-1943",
  "bgna-bul-Cyrl-Latn-2006",
  "bgna-bul-Cyrl-Latn-2009",
  "bgnpcgn-amh-Ethi-Latn-1967",
  "bgnpcgn-ara-Arab-Latn-1956",
  "bgnpcgn-arm-Armn-Latn-1981",
  "bgnpcgn-aze-Cyrl-Latn-1993",
  "bgnpcgn-bak-Cyrl-Latn-2007",
  "bgnpcgn-bal-Arab-Latn-2008",
  "bgnpcgn-bel-Cyrl-Latn-1979",
  "bgnpcgn-bul-Cyrl-Latn-1952",
  "bgnpcgn-bul-Cyrl-Latn-2013",
  "bgnpcgn-che-Cyrl-Latn-2008",
  "bgnpcgn-deu-Latn-Latn-2000",
  "bgnpcgn-div-Thaa-Latn-1972",
  "bgnpcgn-div-Thaa-Latn-1988",
  "bgnpcgn-ell-Grek-Latn-1962",
  "bgnpcgn-ell-Grek-Latn-1996",
  "bgnpcgn-fao-Latn-Latn-1964",
  "bgnpcgn-fao-Latn-Latn-1968",
  "bgnpcgn-fas-Arab-Latn-1956",
  "bgnpcgn-isl-Latn-Latn-1964",
  "bgnpcgn-isl-Latn-Latn-1968",
  "bgnpcgn-jpn-Hrkt-Latn-1976",
  "bgnpcgn-kat-Geor-Latn-1981",
  "bgnpcgn-kat-Geor-Latn-2009",
  "bgnpcgn-kaz-Cyrl-Latn-1979",
  "bgnpcgn-kir-Cyrl-Latn-1979",
  "bgnpcgn-kor-Hang-Latn-kn-1945",
  "bgnpcgn-kor-Hang-Latn-rok-2011",
  "bgnpcgn-kor-Kore-Latn-rok-2011",
  "bgnpcgn-kur-Arab-Latn-2007",
  "bgnpcgn-mkd-Cyrl-Latn-1981",
  "bgnpcgn-mkd-Cyrl-Latn-2013",
  "bgnpcgn-mon-Cyrl-Latn-1964",
  "bgnpcgn-nep-Deva-Latn-2011",
  "bgnpcgn-per-Arab-Latn-1958",
  "bgnpcgn-prs-Arab-Latn-2007",
  "bgnpcgn-prs-Arab-Latn-yaghoubi",
  "bgnpcgn-pus-Arab-Latn-1968",
  "bgnpcgn-ron-Cyrl-Latn-2002",
  "bgnpcgn-rue-Cyrl-Latn-2016",
  "bgnpcgn-rus-Cyrl-Latn-1947",
  "bgnpcgn-sme-Latn-Latn-1984",
  "bgnpcgn-srp-Cyrl-Latn-1962",
  "bgnpcgn-srp-Cyrl-Latn-2005",
  "bgnpcgn-tat-Cyrl-Latn-2007",
  "bgnpcgn-tgk-Cyrl-Latn-1994",
  "bgnpcgn-tir-Ethi-Latn-2007",
  "bgnpcgn-tuk-Cyrl-Latn-1979",
  "bgnpcgn-tuk-Cyrl-Latn-1993",
  "bgnpcgn-ukr-Cyrl-Latn-1965",
  "bgnpcgn-ukr-Cyrl-Latn-2019",
  "bgnpcgn-urd-Arab-Latn-2007",
  "bgnpcgn-uzb-Cyrl-Latn-1979",
  "bgnpcgn-uzb-Cyrl-Latn-2000",
  "bgnpcgn-zho-Hans-Latn-1979",
  "bis-asm-Beng-Latn-13194-1991",
  "bis-ben-Beng-Latn-13194-1991",
  "bis-dev-Deva-Latn-13194-1991",
  "bis-guj-Gujr-Latn-13194-1991",
  "bis-kan-Kana-Latn-13194-1991",
  "bis-mlm-Mlym-Latn-13194-1991",
  "bis-ori-Orya-Latn-13194-1991",
  "bis-pnj-Guru-Latn-13194-1991",
  "bis-tel-Telu-Latn-13194-1991",
  "bis-tml-Taml-Latn-13194-1991",
  "by-bel-Cyrl-Latn-1998",
  "by-bel-Cyrl-Latn-2007",
  "din-grc-Grek-Latn-31634-2011-t1",
  "din-hin-Deva-Latn-33904-2018",
  "din-kat-Geor-Latn-32707-2010",
  "din-mar-Deva-Latn-33904-2018",
  "din-nep-Deva-Latn-33904-2018",
  "din-pli-Deva-Latn-33904-2018",
  "din-pra-Deva-Latn-33904-2018",
  "din-san-Deva-Latn-33904-2018",
  "din-tam-Taml-Latn-33903-2016",
  "dos-nep-Deva-Latn-1997",
  "elot-ell-Grek-Latn-743-1982-tl",
  "elot-ell-Grek-Latn-743-1982-ts",
  "elot-ell-Grek-Latn-743-2001-tl",
  "elot-ell-Grek-Latn-743-2001-ts",
  "ggg-kat-Geor-Latn-2002",
  "gki-bel-Cyrl-Latn-1992",
  "gki-bel-Cyrl-Latn-2000",
  "gost-rus-Cyrl-Latn-16876-71-1983",
  "gost-rus-Cyrl-Latn-7.79-2000-2002",
  "hk-yue-Hani-Latn-1888",
  "icao-bel-Cyrl-Latn-9303",
  "icao-bul-Cyrl-Latn-9303",
  "icao-fas-Arab-Latn-9303",
  "icao-heb-Hebr-Latn-9303",
  "icao-mkd-Cyrl-Latn-9303",
  "icao-rus-Cyrl-Latn-9303",
  "icao-srp-Cyrl-Latn-9303",
  "icao-ukr-Cyrl-Latn-9303",
  "iso-ara-Arab-Latn-233-1984",
  "iso-ara-Arab-Latn-233-2-1993",
  "iso-asm-Beng-Latn-15919-2001",
  "iso-ben-Beng-Latn-15919-2001",
  "iso-ell-Grek-Latn-843-1997-t1",
  "iso-ell-Grek-Latn-843-1997-t2",
  "iso-guj-Gujr-Latn-15919-2001",
  "iso-hin-Deva-Latn-15919-2001",
  "iso-inc-Deva-Latn-15919-2001",
  "iso-jpn-Hrkt-Latn-3602-1989",
  "iso-kan-Kana-Latn-15919-2001",
  "iso-kat-Geor-Latn-9984-1996",
  "iso-kor-Hang-Latn-1996-method1",
  "iso-kor-Hang-Latn-1996-method2",
  "iso-mal-Mlym-Latn-15919-2001",
  "iso-mar-Deva-Latn-15919-2001",
  "iso-nep-Deva-Latn-15919-2001",
  "iso-ori-Orya-Latn-15919-2001",
  "iso-pan-Guru-Latn-15919-2001",
  "iso-pli-Beng-Latn-15919-2001",
  "iso-pli-Deva-Latn-15919-2001",
  "iso-pli-Sinh-Latn-15919-2001",
  "iso-pli-Thai-Latn-15919-2001",
  "iso-pra-Deva-Latn-15919-2001",
  "iso-prs-Arab-Latn-233-3-1999",
  "iso-rus-Cyrl-Latn-9-1995",
  "iso-san-Deva-Latn-15919-2001",
  "iso-tam-Taml-Latn-15919-2001",
  "iso-tel-Telu-Latn-15919-2001",
  "iso-tha-Thai-Latn-11940-1998",
  "kp-kor-Hang-Latn-2002",
  "lshk-yue-Hani-Latn-jyutping-1993",
  "masm-mon-Cyrl-Latn-5217-2012",
  "masm-mon-Latn-Cyrl-5217-2012",
  "mext-jpn-Hrkt-Latn-1954",
  "moct-kor-Hang-Latn-2000",
  "mofa-jpn-Hrkt-Latn-1989",
  "mv-div-Thaa-Latn-1987",
  "mvd-bel-Cyrl-Latn-2008",
  "mvd-bel-Cyrl-Latn-2010",
  "mvd-rus-Cyrl-Latn-2008",
  "mvd-rus-Cyrl-Latn-2010",
  "odni-ara-Arab-Latn-2004",
  "odni-ara-Arab-Latn-2015",
  "odni-aze-Cyrl-Latn-2015",
  "odni-bel-Cyrl-Latn-2015",
  "odni-bul-Cyrl-Latn-2005",
  "odni-bul-Cyrl-Latn-2015",
  "odni-che-Cyrl-Latn-2015",
  "odni-fas-Arab-Latn-2004",
  "odni-fas-Arab-Latn-2015",
  "odni-hin-Deva-Latn-2004",
  "odni-hin-Deva-Latn-2015",
  "odni-kat-Geor-Latn-2015",
  "odni-kaz-Cyrl-Latn-2015",
  "odni-kir-Cyrl-Latn-2015",
  "odni-kor-Hang-Latn-2015",
  "odni-mkd-Cyrl-Latn-2005",
  "odni-mkd-Cyrl-Latn-2015",
  "odni-prs-Arab-Latn-2004",
  "odni-prs-Arab-Latn-2015",
  "odni-pus-Arab-Latn-2011",
  "odni-rus-Cyrl-Latn-2015",
  "odni-srp-Cyrl-Latn-2005",
  "odni-srp-Cyrl-Latn-2015",
  "odni-tat-Cyrl-Latn-2015",
  "odni-tgk-Cyrl-Latn-2015",
  "odni-tuk-Cyrl-Latn-2015",
  "odni-uig-Cyrl-Latn-2015",
  "odni-ukr-Cyrl-Latn-2015",
  "odni-urd-Arab-Latn-2015",
  "odni-uzb-Cyrl-Latn-2015",
  "sac-zho-Hans-Latn-1979",
  "sasm-mon-Mong-Latn-general-1978",
  "sasm-mon-Mong-Latn-phonetic-1978",
  "ses-ara-Arab-Latn-1930",
  "stategeocadastre-ukr-Cyrl-Latn-1993",
  "ua-ukr-Cyrl-Latn-1996",
  "ua-ukr-Cyrl-Latn-2007",
  "ua-ukr-Cyrl-Latn-2010",
  "un-amh-Ethi-Latn-2016",
  "un-ara-Arab-Latn-1971",
  "un-ara-Arab-Latn-1972",
  "un-ara-Arab-Latn-2017",
  "un-asm-Beng-Latn-1972",
  "un-bel-Cyrl-Latn-2007",
  "un-ben-Beng-Latn-2016",
  "un-bul-Cyrl-Latn-1977",
  "un-ell-Grek-Latn-1987-phonetic",
  "un-ell-Grek-Latn-1987-tl",
  "un-ell-Grek-Latn-1987-ts",
  "un-guj-Gujr-Latn-1972",
  "un-hin-Deva-Latn-2016",
  "un-kan-Kana-Latn-2016",
  "un-mal-Mlym-Latn-1972",
  "un-mar-Deva-Latn-2016",
  "un-mkd-Cyrl-Latn-1977",
  "un-mon-Mong-Latn-general-2013",
  "un-mon-Mong-Latn-phonetic-2013",
  "un-nep-Deva-Latn-1972",
  "un-nep-Deva-Latn-2013",
  "un-ori-Orya-Latn-1972",
  "un-pan-Guru-Latn-1972",
  "un-prs-Arab-Latn-1967",
  "un-rus-Cyrl-Latn-1987",
  "un-sin-Sinh-Latn-1972",
  "un-srp-Cyrl-Latn-1997",
  "un-tam-Taml-Latn-1972",
  "un-tel-Telu-Latn-1972",
  "un-ukr-Cyrl-Latn-1998",
  "un-ukr-Cyrl-Latn-2012",
  "un-urd-Arab-Latn-1972",
  "var-amh-Ethi-Latn-eae-2003",
  "var-ara-Arab-Arab-rababa",
  "var-gez-Ethi-Latn-eae-2003",
  "var-hin-Deva-Latn-hunterian-1872",
  "var-jpn-Hrkt-Latn-hepburn-1886",
  "var-jpn-Hrkt-Latn-hepburn-1954",
  "var-kor-Hang-Hang-jamo",
  "var-kor-Hang-Latn-mr-1939",
  "var-kor-Kore-Hang-2013",
  "var-kor-Kore-Latn-mr-1939",
  "var-mar-Deva-Latn-hunterian-1872",
  "var-mon-Mong-Latn-1930",
  "var-mon-Mong-Latn-lessing",
  "var-mon-Mong-Latn-vpmc",
  "var-pra-Deva-Latn-iast-1912",
  "var-san-Deva-Latn-iast-1912",
  "var-zho-Hani-Latn-wd-1979"
] as const

export const maps: Record<string, unknown> = {
  acadsin-zho-Hani-Latn-2002: m0,
  alalc-amh-Ethi-Latn-1997: m1,
  alalc-amh-Ethi-Latn-2011: m2,
  alalc-ara-Arab-Latn-1997: m3,
  alalc-asm-Deva-Latn-1997: m4,
  alalc-asm-Deva-Latn-2012: m5,
  alalc-aze-Arab-Latn-1997: m6,
  alalc-aze-Cyrl-Latn-1997: m7,
  alalc-bel-Cyrl-Latn-1997: m8,
  alalc-ben-Beng-Latn-1997: m9,
  alalc-ben-Beng-Latn-2017: m10,
  alalc-bul-Cyrl-Latn-1997: m11,
  alalc-div-Thaa-Latn-1997: m12,
  alalc-div-Thaa-Latn-2012: m13,
  alalc-ell-Grek-Latn-1997: m14,
  alalc-ell-Grek-Latn-2010: m15,
  alalc-fas-Arab-Latn-1997: m16,
  alalc-guj-Gujr-Latn-1997: m17,
  alalc-guj-Gujr-Latn-2011: m18,
  alalc-hin-Deva-Latn-1997: m19,
  alalc-hin-Deva-Latn-2011: m20,
  alalc-kan-Kana-Latn-1997: m21,
  alalc-kan-Kana-Latn-2011: m22,
  alalc-kat-Geok-Latn-1997: m23,
  alalc-kat-Geok-Latn-2011: m24,
  alalc-kat-Geor-Latn-1997: m25,
  alalc-kat-Geor-Latn-2011: m26,
  alalc-kor-Hang-Latn-1997: m27,
  alalc-mal-Mlym-Latn-1997: m28,
  alalc-mal-Mlym-Latn-2012: m29,
  alalc-mar-Deva-Latn-1997: m30,
  alalc-mar-Deva-Latn-2011: m31,
  alalc-mkd-Cyrl-Latn-1997: m32,
  alalc-mkd-Cyrl-Latn-2013: m33,
  alalc-mon-Cyrl-Latn-1997: m34,
  alalc-ori-Orya-Latn-1997: m35,
  alalc-ori-Orya-Latn-2011: m36,
  alalc-pan-Guru-Latn-1997: m37,
  alalc-pan-Guru-Latn-2011: m38,
  alalc-pli-Deva-Latn-2012: m39,
  alalc-pra-Deva-Latn-2012: m40,
  alalc-rus-Cyrl-Latn-1997: m41,
  alalc-rus-Cyrl-Latn-2012: m42,
  alalc-san-Deva-Latn-2012: m43,
  alalc-sin-Sinh-Latn-1997: m44,
  alalc-sin-Sinh-Latn-2011: m45,
  alalc-srp-Cyrl-Latn-1997: m46,
  alalc-srp-Cyrl-Latn-2013: m47,
  alalc-tam-Taml-Latn-1997: m48,
  alalc-tam-Taml-Latn-2011: m49,
  alalc-tel-Telu-Latn-1997: m50,
  alalc-tel-Telu-Latn-2011: m51,
  alalc-tir-Ethi-Latn-1997: m52,
  alalc-tir-Ethi-Latn-2011: m53,
  alalc-ukr-Cyrl-Latn-1997: m54,
  alalc-ukr-Cyrl-Latn-2011: m55,
  apcbg-bul-Cyrl-Latn-1995: m56,
  az-aze-Cyrl-Latn-1939: m57,
  az-aze-Cyrl-Latn-1958: m58,
  bas-rus-Cyrl-Latn-2017-bss: m59,
  bas-rus-Cyrl-Latn-2017-oss: m60,
  bgn-jpn-Hrkt-Latn-1962: m61,
  bgn-kor-Hang-Latn-1943: m62,
  bgn-kor-Kore-Latn-1943: m63,
  bgna-bul-Cyrl-Latn-2006: m64,
  bgna-bul-Cyrl-Latn-2009: m65,
  bgnpcgn-amh-Ethi-Latn-1967: m66,
  bgnpcgn-ara-Arab-Latn-1956: m67,
  bgnpcgn-arm-Armn-Latn-1981: m68,
  bgnpcgn-aze-Cyrl-Latn-1993: m69,
  bgnpcgn-bak-Cyrl-Latn-2007: m70,
  bgnpcgn-bal-Arab-Latn-2008: m71,
  bgnpcgn-bel-Cyrl-Latn-1979: m72,
  bgnpcgn-bul-Cyrl-Latn-1952: m73,
  bgnpcgn-bul-Cyrl-Latn-2013: m74,
  bgnpcgn-che-Cyrl-Latn-2008: m75,
  bgnpcgn-deu-Latn-Latn-2000: m76,
  bgnpcgn-div-Thaa-Latn-1972: m77,
  bgnpcgn-div-Thaa-Latn-1988: m78,
  bgnpcgn-ell-Grek-Latn-1962: m79,
  bgnpcgn-ell-Grek-Latn-1996: m80,
  bgnpcgn-fao-Latn-Latn-1964: m81,
  bgnpcgn-fao-Latn-Latn-1968: m82,
  bgnpcgn-fas-Arab-Latn-1956: m83,
  bgnpcgn-isl-Latn-Latn-1964: m84,
  bgnpcgn-isl-Latn-Latn-1968: m85,
  bgnpcgn-jpn-Hrkt-Latn-1976: m86,
  bgnpcgn-kat-Geor-Latn-1981: m87,
  bgnpcgn-kat-Geor-Latn-2009: m88,
  bgnpcgn-kaz-Cyrl-Latn-1979: m89,
  bgnpcgn-kir-Cyrl-Latn-1979: m90,
  bgnpcgn-kor-Hang-Latn-kn-1945: m91,
  bgnpcgn-kor-Hang-Latn-rok-2011: m92,
  bgnpcgn-kor-Kore-Latn-rok-2011: m93,
  bgnpcgn-kur-Arab-Latn-2007: m94,
  bgnpcgn-mkd-Cyrl-Latn-1981: m95,
  bgnpcgn-mkd-Cyrl-Latn-2013: m96,
  bgnpcgn-mon-Cyrl-Latn-1964: m97,
  bgnpcgn-nep-Deva-Latn-2011: m98,
  bgnpcgn-per-Arab-Latn-1958: m99,
  bgnpcgn-prs-Arab-Latn-2007: m100,
  bgnpcgn-prs-Arab-Latn-yaghoubi: m101,
  bgnpcgn-pus-Arab-Latn-1968: m102,
  bgnpcgn-ron-Cyrl-Latn-2002: m103,
  bgnpcgn-rue-Cyrl-Latn-2016: m104,
  bgnpcgn-rus-Cyrl-Latn-1947: m105,
  bgnpcgn-sme-Latn-Latn-1984: m106,
  bgnpcgn-srp-Cyrl-Latn-1962: m107,
  bgnpcgn-srp-Cyrl-Latn-2005: m108,
  bgnpcgn-tat-Cyrl-Latn-2007: m109,
  bgnpcgn-tgk-Cyrl-Latn-1994: m110,
  bgnpcgn-tir-Ethi-Latn-2007: m111,
  bgnpcgn-tuk-Cyrl-Latn-1979: m112,
  bgnpcgn-tuk-Cyrl-Latn-1993: m113,
  bgnpcgn-ukr-Cyrl-Latn-1965: m114,
  bgnpcgn-ukr-Cyrl-Latn-2019: m115,
  bgnpcgn-urd-Arab-Latn-2007: m116,
  bgnpcgn-uzb-Cyrl-Latn-1979: m117,
  bgnpcgn-uzb-Cyrl-Latn-2000: m118,
  bgnpcgn-zho-Hans-Latn-1979: m119,
  bis-asm-Beng-Latn-13194-1991: m120,
  bis-ben-Beng-Latn-13194-1991: m121,
  bis-dev-Deva-Latn-13194-1991: m122,
  bis-guj-Gujr-Latn-13194-1991: m123,
  bis-kan-Kana-Latn-13194-1991: m124,
  bis-mlm-Mlym-Latn-13194-1991: m125,
  bis-ori-Orya-Latn-13194-1991: m126,
  bis-pnj-Guru-Latn-13194-1991: m127,
  bis-tel-Telu-Latn-13194-1991: m128,
  bis-tml-Taml-Latn-13194-1991: m129,
  by-bel-Cyrl-Latn-1998: m130,
  by-bel-Cyrl-Latn-2007: m131,
  din-grc-Grek-Latn-31634-2011-t1: m132,
  din-hin-Deva-Latn-33904-2018: m133,
  din-kat-Geor-Latn-32707-2010: m134,
  din-mar-Deva-Latn-33904-2018: m135,
  din-nep-Deva-Latn-33904-2018: m136,
  din-pli-Deva-Latn-33904-2018: m137,
  din-pra-Deva-Latn-33904-2018: m138,
  din-san-Deva-Latn-33904-2018: m139,
  din-tam-Taml-Latn-33903-2016: m140,
  dos-nep-Deva-Latn-1997: m141,
  elot-ell-Grek-Latn-743-1982-tl: m142,
  elot-ell-Grek-Latn-743-1982-ts: m143,
  elot-ell-Grek-Latn-743-2001-tl: m144,
  elot-ell-Grek-Latn-743-2001-ts: m145,
  ggg-kat-Geor-Latn-2002: m146,
  gki-bel-Cyrl-Latn-1992: m147,
  gki-bel-Cyrl-Latn-2000: m148,
  gost-rus-Cyrl-Latn-16876-71-1983: m149,
  gost-rus-Cyrl-Latn-7.79-2000-2002: m150,
  hk-yue-Hani-Latn-1888: m151,
  icao-bel-Cyrl-Latn-9303: m152,
  icao-bul-Cyrl-Latn-9303: m153,
  icao-fas-Arab-Latn-9303: m154,
  icao-heb-Hebr-Latn-9303: m155,
  icao-mkd-Cyrl-Latn-9303: m156,
  icao-rus-Cyrl-Latn-9303: m157,
  icao-srp-Cyrl-Latn-9303: m158,
  icao-ukr-Cyrl-Latn-9303: m159,
  iso-ara-Arab-Latn-233-1984: m160,
  iso-ara-Arab-Latn-233-2-1993: m161,
  iso-asm-Beng-Latn-15919-2001: m162,
  iso-ben-Beng-Latn-15919-2001: m163,
  iso-ell-Grek-Latn-843-1997-t1: m164,
  iso-ell-Grek-Latn-843-1997-t2: m165,
  iso-guj-Gujr-Latn-15919-2001: m166,
  iso-hin-Deva-Latn-15919-2001: m167,
  iso-inc-Deva-Latn-15919-2001: m168,
  iso-jpn-Hrkt-Latn-3602-1989: m169,
  iso-kan-Kana-Latn-15919-2001: m170,
  iso-kat-Geor-Latn-9984-1996: m171,
  iso-kor-Hang-Latn-1996-method1: m172,
  iso-kor-Hang-Latn-1996-method2: m173,
  iso-mal-Mlym-Latn-15919-2001: m174,
  iso-mar-Deva-Latn-15919-2001: m175,
  iso-nep-Deva-Latn-15919-2001: m176,
  iso-ori-Orya-Latn-15919-2001: m177,
  iso-pan-Guru-Latn-15919-2001: m178,
  iso-pli-Beng-Latn-15919-2001: m179,
  iso-pli-Deva-Latn-15919-2001: m180,
  iso-pli-Sinh-Latn-15919-2001: m181,
  iso-pli-Thai-Latn-15919-2001: m182,
  iso-pra-Deva-Latn-15919-2001: m183,
  iso-prs-Arab-Latn-233-3-1999: m184,
  iso-rus-Cyrl-Latn-9-1995: m185,
  iso-san-Deva-Latn-15919-2001: m186,
  iso-tam-Taml-Latn-15919-2001: m187,
  iso-tel-Telu-Latn-15919-2001: m188,
  iso-tha-Thai-Latn-11940-1998: m189,
  kp-kor-Hang-Latn-2002: m190,
  lshk-yue-Hani-Latn-jyutping-1993: m191,
  masm-mon-Cyrl-Latn-5217-2012: m192,
  masm-mon-Latn-Cyrl-5217-2012: m193,
  mext-jpn-Hrkt-Latn-1954: m194,
  moct-kor-Hang-Latn-2000: m195,
  mofa-jpn-Hrkt-Latn-1989: m196,
  mv-div-Thaa-Latn-1987: m197,
  mvd-bel-Cyrl-Latn-2008: m198,
  mvd-bel-Cyrl-Latn-2010: m199,
  mvd-rus-Cyrl-Latn-2008: m200,
  mvd-rus-Cyrl-Latn-2010: m201,
  odni-ara-Arab-Latn-2004: m202,
  odni-ara-Arab-Latn-2015: m203,
  odni-aze-Cyrl-Latn-2015: m204,
  odni-bel-Cyrl-Latn-2015: m205,
  odni-bul-Cyrl-Latn-2005: m206,
  odni-bul-Cyrl-Latn-2015: m207,
  odni-che-Cyrl-Latn-2015: m208,
  odni-fas-Arab-Latn-2004: m209,
  odni-fas-Arab-Latn-2015: m210,
  odni-hin-Deva-Latn-2004: m211,
  odni-hin-Deva-Latn-2015: m212,
  odni-kat-Geor-Latn-2015: m213,
  odni-kaz-Cyrl-Latn-2015: m214,
  odni-kir-Cyrl-Latn-2015: m215,
  odni-kor-Hang-Latn-2015: m216,
  odni-mkd-Cyrl-Latn-2005: m217,
  odni-mkd-Cyrl-Latn-2015: m218,
  odni-prs-Arab-Latn-2004: m219,
  odni-prs-Arab-Latn-2015: m220,
  odni-pus-Arab-Latn-2011: m221,
  odni-rus-Cyrl-Latn-2015: m222,
  odni-srp-Cyrl-Latn-2005: m223,
  odni-srp-Cyrl-Latn-2015: m224,
  odni-tat-Cyrl-Latn-2015: m225,
  odni-tgk-Cyrl-Latn-2015: m226,
  odni-tuk-Cyrl-Latn-2015: m227,
  odni-uig-Cyrl-Latn-2015: m228,
  odni-ukr-Cyrl-Latn-2015: m229,
  odni-urd-Arab-Latn-2015: m230,
  odni-uzb-Cyrl-Latn-2015: m231,
  sac-zho-Hans-Latn-1979: m232,
  sasm-mon-Mong-Latn-general-1978: m233,
  sasm-mon-Mong-Latn-phonetic-1978: m234,
  ses-ara-Arab-Latn-1930: m235,
  stategeocadastre-ukr-Cyrl-Latn-1993: m236,
  ua-ukr-Cyrl-Latn-1996: m237,
  ua-ukr-Cyrl-Latn-2007: m238,
  ua-ukr-Cyrl-Latn-2010: m239,
  un-amh-Ethi-Latn-2016: m240,
  un-ara-Arab-Latn-1971: m241,
  un-ara-Arab-Latn-1972: m242,
  un-ara-Arab-Latn-2017: m243,
  un-asm-Beng-Latn-1972: m244,
  un-bel-Cyrl-Latn-2007: m245,
  un-ben-Beng-Latn-2016: m246,
  un-bul-Cyrl-Latn-1977: m247,
  un-ell-Grek-Latn-1987-phonetic: m248,
  un-ell-Grek-Latn-1987-tl: m249,
  un-ell-Grek-Latn-1987-ts: m250,
  un-guj-Gujr-Latn-1972: m251,
  un-hin-Deva-Latn-2016: m252,
  un-kan-Kana-Latn-2016: m253,
  un-mal-Mlym-Latn-1972: m254,
  un-mar-Deva-Latn-2016: m255,
  un-mkd-Cyrl-Latn-1977: m256,
  un-mon-Mong-Latn-general-2013: m257,
  un-mon-Mong-Latn-phonetic-2013: m258,
  un-nep-Deva-Latn-1972: m259,
  un-nep-Deva-Latn-2013: m260,
  un-ori-Orya-Latn-1972: m261,
  un-pan-Guru-Latn-1972: m262,
  un-prs-Arab-Latn-1967: m263,
  un-rus-Cyrl-Latn-1987: m264,
  un-sin-Sinh-Latn-1972: m265,
  un-srp-Cyrl-Latn-1997: m266,
  un-tam-Taml-Latn-1972: m267,
  un-tel-Telu-Latn-1972: m268,
  un-ukr-Cyrl-Latn-1998: m269,
  un-ukr-Cyrl-Latn-2012: m270,
  un-urd-Arab-Latn-1972: m271,
  var-amh-Ethi-Latn-eae-2003: m272,
  var-ara-Arab-Arab-rababa: m273,
  var-gez-Ethi-Latn-eae-2003: m274,
  var-hin-Deva-Latn-hunterian-1872: m275,
  var-jpn-Hrkt-Latn-hepburn-1886: m276,
  var-jpn-Hrkt-Latn-hepburn-1954: m277,
  var-kor-Hang-Hang-jamo: m278,
  var-kor-Hang-Latn-mr-1939: m279,
  var-kor-Kore-Hang-2013: m280,
  var-kor-Kore-Latn-mr-1939: m281,
  var-mar-Deva-Latn-hunterian-1872: m282,
  var-mon-Mong-Latn-1930: m283,
  var-mon-Mong-Latn-lessing: m284,
  var-mon-Mong-Latn-vpmc: m285,
  var-pra-Deva-Latn-iast-1912: m286,
  var-san-Deva-Latn-iast-1912: m287,
  var-zho-Hani-Latn-wd-1979: m288,
}
