#!/usr/bin/env ruby
# Compiles the .isc corpus to JSON IR using interscript-ruby's JsonIR
# compiler — the schema-versioned IR interscript-ts consumes. Run from
# the api repo root; requires the interscript-ruby and interscript-maps
# checkouts (or gems).
#
#   ruby scripts/build-maps.rb /path/to/interscript-ruby /path/to/maps maps/
#
# Output: maps/<system_code>.json per map + maps/index.js (registry).
# The JSON corpus is committed: bundled maps are cheap, immutable per
# release, and cacheable by any deployer.

require "json"
require "fileutils"

ruby_root, maps_root, out_dir = ARGV
abort "usage: build-maps.rb <interscript-ruby> <maps-repo> <out-dir>" unless maps_root && out_dir

$LOAD_PATH.unshift(File.join(ruby_root, "lib"))
require "interscript"
require "interscript/compiler/json_ir"

FileUtils.mkdir_p(out_dir)
codes = Dir.glob(File.join(maps_root, "maps", "*.isc")).map do |path|
  code = File.basename(path, ".isc")
  map = Interscript.load_map!(code, path: File.join(maps_root, "maps"))
  json = Interscript::Compiler::JsonIR.new.compile(map).code
  File.write(File.join(out_dir, "#{code}.json"), json)
  code
end

index = +"// Generated by scripts/build-maps.rb — do not edit.\n"
codes.sort.each_with_index do |code, i|
  index << "import m#{i} from \"./#{code}.json\" with { type: \"json\" }\n"
end
index << "\nexport const systemCodes = #{JSON.pretty_generate(codes.sort)} as const\n\n"
index << "export const maps: Record<string, unknown> = {\n"
codes.sort.each_with_index do |code, i|
  index << "  #{code.to_sym}: m#{i},\n"
end
index << "}\n"
File.write(File.join(out_dir, "index.js"), index)
puts "compiled #{codes.length} maps to #{out_dir}"
