#!/usr/bin/env node
// Rebuild the bundled maps corpus from the canonical builder — the
// interscript-ts ISC parser/converter, the same pipeline that produces
// the interscript/maps release artifact (interscript.maps.ir.v1).
//
// Usage (from the api repo root):
//   node scripts/build-maps.mjs <interscript-maps-dir> <interscript-ts-dir>
//
// Writes maps/<system>.json (289 systems) and regenerates
// maps/manifest.js. The corpus is committed: tests replay parity
// fixtures against it, and the deploy fetches the byte-identical
// release artifact (scripts/fetch-maps-artifact.mjs lives in the
// deploy repo).

import { execFileSync } from "node:child_process"
import { copyFileSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs"
import { basename, join, resolve } from "node:path"

const [mapsDir, tsDir] = process.argv.slice(2)
if (!mapsDir || !tsDir) {
  console.error("usage: build-maps.mjs <interscript-maps-dir> <interscript-ts-dir>")
  process.exit(2)
}

const repoRoot = resolve(import.meta.dirname, "..")
const outDir = resolve(repoRoot, ".maps-artifact")
const outMaps = join(outDir, "maps")

rmSync(outDir, { recursive: true, force: true })
execFileSync("npx", ["-y", "tsx", "scripts/build-json-ir-artifact.mjs", resolve(tsDir), outDir], {
  cwd: resolve(mapsDir),
  stdio: "inherit",
})

const manifest = JSON.parse(readFileSync(join(outDir, "manifest.json"), "utf8"))
if (manifest.schema !== "interscript.maps.ir.v1") {
  throw new Error(`unexpected artifact schema ${manifest.schema}`)
}

const repoMaps = join(repoRoot, "maps")
for (const name of readdirSync(repoMaps)) {
  if (name.endsWith(".json")) rmSync(join(repoMaps, name))
}
for (const name of readdirSync(outMaps)) copyFileSync(join(outMaps, name), join(repoMaps, name))

writeFileSync(
  join(repoMaps, "manifest.js"),
  `// Generated by scripts/build-maps.mjs from interscript/maps (${manifest.count} systems). Do not edit.\n` +
    `export const systemCodes = ${JSON.stringify(manifest.systems)};\n`,
)
writeFileSync(join(repoMaps, "manifest.d.ts"), "export const systemCodes: readonly string[]\n")

const mapScripts = {}
for (const name of readdirSync(outMaps)) {
  const code = basename(name, ".json")
  if (manifest.systems.includes(code)) {
    mapScripts[code] = JSON.parse(readFileSync(join(outMaps, name), "utf8")).metadata?.source_script
  }
}
writeFileSync(
  join(repoMaps, "scripts.js"),
  "// Generated by scripts/build-maps.mjs from interscript/maps — source script per system. Do not edit.\n" +
    `export const mapScripts = ${JSON.stringify(mapScripts)};\n`,
)
writeFileSync(
  join(repoMaps, "scripts.d.ts"),
  "export const mapScripts: Record<string, string | undefined>\n",
)

rmSync(outDir, { recursive: true, force: true })
console.log(`bundled ${manifest.count} maps into maps/`)
